Last changes
alvarochapela/zrive-ds pull request #1
Opened 2023-09-29 13:28 UTC by alvarochapela

PR del modulo 1 como me indicó Pablo

2023-09-30 18:12 UTC, pabaldonedo commented
I made a mistake when doing the reverts to keep the main clean and creating this one. That's why you may see some commits now of my own. Howver, the code was kept exactly the same as you had it.

2023-09-30 18:25 UTC, pabaldonedo requested changes
This is the teachers solutions. While it is good that you review it and try it yourself, the point of the PRs is that you get personalised feedback of your work so you can spot your weaknesses and learn

For example, in the files that were submitted by you I have made some comments that may be useful for you in the future

2023-09-30 18:25 UTC, pabaldonedo commented on .DS_Store
NEVER add these kind of files to git.

You can use the [`.gitignore`](https://git-scm.com/docs/gitignore) file to automatically ignore certain files

2023-09-30 18:25 UTC, pabaldonedo commented on src/.DS_Store
same comment as before

2023-09-30 18:25 UTC, pabaldonedo commented on src/Homework1.py
There are two files with the same name, this should not be the case. I'm reviewing the one inside module_1 folder

2023-09-30 18:25 UTC, pabaldonedo commented on src/__init__.py
This is dummy content that should be removed

2023-09-30 18:25 UTC, pabaldonedo commented on src/module_1/Homework1.py
following naming conventions [PEP8](https://peps.python.org/pep-0008/) filenames should be lowercase

2023-09-30 18:25 UTC, pabaldonedo commented on src/module_1/module_1_meteo_api.py
Either submit the solution here or remove this file

2023-09-30 18:25 UTC, pabaldonedo commented on src/module_1/Homework1.py
This is the teachers solutions. While it is good that you review it and try it yourself, the point of the PRs is that you get personalised feedback of your work so you can spot your weaknesses and learn

2023-09-30 22:11 UTC, alvarochapela reviewed
Everything reviewed

2023-10-01 10:42 UTC, pabaldonedo requested changes

2023-10-01 10:42 UTC, pabaldonedo commented on src/__init__.py
The dummy content to be removed was the internals of the file, not te file in itself. If you are unfamiliar with __init__ files check [this](https://docs.python.org/3/reference/import.html#regular-packages). Please restore this file but with empty content

2023-10-01 10:42 UTC, pabaldonedo commented on src/module_1/__init__.py
same here

2023-10-01 11:06 UTC, pabaldonedo approved these changes

2023-10-01 11:07 UTC, pabaldonedo approved these changes

2023-10-01 11:08 UTC, merged